[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs"]

# Tambahkan agar nodejs juga tersedia di runtime container
runtimePkgs = ["php", "nodejs"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm install",
  "npm run build"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
